[package]
name = "test"
version = "0.1.0"
edition = "2024"

[dependencies]
maud = "0.27.0"
rejoice = "0.12.3"
tokio = { version = "1.48.0", features = ["full"] }

[build-dependencies]
rejoice = "0.12.3"
